### ISSUE TITLE
Client example with GET requests

### ISSUE THREAD

**Issue by misuzu** [python-hyper/hyper-h2#1027]
Such simple use case not covered at all

**Comment by Lukasa** [comment]
I recommend using the [HEAD](https://python-hyper.org/h2/en/stable/twisted-head-example.html) example and changing the method.

**Comment by misuzu** [comment]
@Lukasa well, i can't get it to work correctly. It just hangs after 64k of downloaded data.

**Comment by vladmunteanu** [comment]
@misuzu you should probably update the window size so that the other side will now you are able to receive more data.

More details about this [here](https://python-hyper.org/projects/h2/en/stable/advanced-usage.html#flow-control).

**Comment by misuzu** [comment]
@vladmunteanu thanks! I had to call acknowledge_received_data on DataReceived event. Now it working correctly.
