### ISSUE TITLE
H2Connection initial settings should be customizable

### ISSUE THREAD

**Issue by vladmunteanu** [python-hyper/hyper-h2#1042]
For simple use cases where the user calls ``H2Connection.initiate_connection()`` and then ``H2Connection.update_settings()``, it can be noticed that 2 settings frames will be sent.

The first one contains the defaults, generated in the ``initiate_connection()`` call.
The second frame contains any user updated settings.

While this behaviour does not violate the HTTP/2 specifications, I think we can accept some settings in the H2Connection ``__init__`` method to allow users to control the initial settings.
If the required settings are not provided, H2Connection can use the defaults.

**Comment by Lukasa** [comment]
So while we certainly *could* accept settings in the `__init__`, it's not really entirely necessary. For the general situation it's unlikely to matter, and for those that need it they can simply patch the `H2Connection.local_settings` member with a new `Settings` object.

That said, I think I'd probably be willing to accept a tested patch that enables this: I just don't think it's particularly high priority. :smile:

**Comment by vladmunteanu** [comment]
Yep, agreed, i'll try some things.
It's odd that ENABLE_PUSH is set by default, in my opinion. It seems like a difficult feature to implement and I imagine more simple clients will not do it.

**Comment by Lukasa** [comment]
`ENABLE_PUSH` is set by default because HTTP/2 does so. No more substantial reason. :smile:

**Comment by vladmunteanu** [comment]
@Lukasa makes sense 😊. I didn't know that when i opened the issue, thanks 😄 .
I guess you can close this issue if you think so.

**Comment by Lukasa** [comment]
:+1: Thanks for your input!
