### ISSUE TITLE
[Question] How can I use the examples thru curl?

### ISSUE THREAD

**Issue by japrogramer** [python-hyper/hyper-h2#1043]
Hello, I am trying to run the asyncio-server.py example but when I try to post to it I get this error.
```
➜  curl-7.56.1 curl -H "Content-Type: application/json" -X POST -d '{"username":"xyz","password":"xyz"}' --http2 http://127.0.0.1:8443                                                                         
curl: (52) Empty reply from server 
```
When I visit the address thru a browser I receive a ERR_EMPTY_RESPONSE
Are some examples on how to contact the server?

**Comment by japrogramer** [comment]
hmm, looks like i need it to pass in some ca certs

**Comment by Lukasa** [comment]
Yup, the certs are necessary for the example to work.
