### ISSUE TITLE
There are some faults in the basic-usage.rst

### ISSUE THREAD

**Issue by breadsh** [python-hyper/hyper-h2#1044]
There are some faults in the doc. 
I think it should be 
**config = h2.config.H2Configuration(client_side=False)
conn = h2.connection.H2Connection(config=config)**
#
not just 
**conn = h2.connection.H2Connection(client_side=False)**

also I am not very sure the result is correct.
**[<h2.events.RemoteSettingsChanged object at 0x10c4ee390>]**

because I got the result below:
**[<RemoteSettingsChanged changed_settings:{ChangedSetting(setting=SettingCodes.HEADER_TABLE_SIZE, original_value=4096, new_value=4096), ChangedSetting(setting=SettingCodes.ENABLE_PUSH, original_value=1, new_value=1), ChangedSetting(setting=SettingCodes.MAX_CONCURRENT_STREAMS, original_value=None, new_value=100), ChangedSetting(setting=SettingCodes.INITIAL_WINDOW_SIZE, original_value=65535, new_value=65535), ChangedSetting(setting=SettingCodes.MAX_FRAME_SIZE, original_value=16384, new_value=16384), ChangedSetting(setting=SettingCodes.MAX_HEADER_LIST_SIZE, original_value=None, new_value=65536)}>, <RemoteSettingsChanged changed_settings:{ChangedSetting(setting=SettingCodes.ENABLE_PUSH, original_value=1, new_value=0)}>]
[<SettingsAcknowledged changed_settings:{}>]**

**Comment by Kriechi** [comment]
Please reopen if you think this is still an issue and report with line numbers or paragraph in the docs.
