### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by frnkvieira** [python-hyper/hyper-h2#1105]
Hi @Lukasa !
I'm developing a new framework like Flask/Sanic (currently 5x faster than Sanic on real-world use cases :P) and I'm really excited about adding HTTP2 features. I thought about implementing this on my own but your library seems awesome (and it's hell hard to do correctly lol) !
I'm worried about this HTTP2 implementation will slow down a lot my framework thanks to being pure Python (my framework make heavy use of Cython).
Do you have any benchmarks or related material ? 
(Tried to do my own using this example https://github.com/python-hyper/hyper-h2/blob/master/examples/asyncio/asyncio-server.py and, although it runs, the response is empty. Not sure if I messed up)

Anyway, thanks for the good work!

**Comment by Lukasa** [comment]
Thanks for your interest!

In CPython there is no two ways about it, h2 is slower than a native code implementation of HTTP/2. Last I looked it seemed like, on localhost using CPython, h2 was about 4 orders of magnitude slower than nghttpd. (PyPy improves this story to one order of magnitude.)

*However*, there is good news here: when you add a real network into the mix things get better. You see, most web servers don’t come close to saturating the network, so there is a bunch of idle time. Spending a bit more time doing the processing in Python tends not to blow the performance budget. 

That said, I highly encourage you to benchmark for your own usecase!

**Comment by frnkvieira** [comment]
Thanks!
