### ISSUE TITLE
Documentation and examples reference http2bin.org

### ISSUE THREAD

**Issue by erm** [python-hyper/hyper-h2#1155]
The documentation and some of the example files reference http2bin.org which is no longer maintained according to discussion here https://github.com/requests/httpbin/issues/309#issuecomment-339558664 and indicates to use http://nghttp2.org/httpbin as an alternative.

**Comment by pgjones** [comment]
Complete in aaa0ad0cfc118fddef5ca0aa24d3104ac0ba069d
