### ISSUE TITLE
getting this error     from enum import Enum, IntEnum ImportError: cannot import name IntEnum

### ISSUE THREAD

**Issue by markmark1** [python-hyper/hyper-h2#1159]
from enum import Enum, IntEnum
ImportError: cannot import name IntEnum

**Comment by alexwlchan** [comment]
My guess would be that you have the wrong version of `enum` installed.

Can you run `python --version` and `pip freeze`, and paste the results here?

**Comment by davincif** [comment]
I'm having having this issue on

python --version
`Python 3.6.8`

and, pip freeze
`falcon==2.0.0
gunicorn==19.9.0`

**Comment by pgjones** [comment]
@davincif Very strange as the [library was added in Python 3.4](https://docs.python.org/3/library/enum.html). I think this must be an issue with your local setup - are you using h2?
