### ISSUE TITLE
State machine emits too generic errors

### ISSUE THREAD

**Issue by Kriechi** [python-hyper/hyper-h2#116]
Calling `h2.reset_stream(...)` on an already closed streams gives me an `ProtocolError`, but since there is a `StreamClosedError` in hyper-h2, I would have expected to get this.

Trace of error:
```
  File ".../hyper-h2/h2/connection.py", line 680, in reset_stream
    frames = stream.reset_stream(error_code)
  File ".../hyper-h2/h2/stream.py", line 730, in reset_stream
    self.state_machine.process_input(StreamInputs.SEND_RST_STREAM)
  File ".../hyper-h2/h2/stream.py", line 98, in process_input
    "Invalid input %s in state %s" % (input_, old_state)
ProtocolError: Invalid input StreamInputs.SEND_RST_STREAM in state StreamState.CLOSED
```

Is it possible to handle/check all errors for the correct exception class and emit the best fit?
Otherwise I need to catch multiple error classes, where a single one would have done the job.

**Comment by Lukasa** [comment]
I think this is an oversight in the state machine. I think all SEND_* inputs in the CLOSED state should raise the StreamClosedError. Should be an easy fix. =)

**Comment by Lukasa** [comment]
See #118.
