### ISSUE TITLE
Stream closed or not yet created?

### ISSUE THREAD

**Issue by Kriechi** [python-hyper/hyper-h2#117]
Since `get_stream_by_id` got removed from the public API, I would like to get some way to check if a stream is closed, or does not yet exist, e.g. [this distinction](https://github.com/python-hyper/hyper-h2/blob/f8b2001a47246b3baffc0673d6f12fbe34fc50db/h2/connection.py#L430-L433).

The problem is because (for memory cleanup reasons?) closed streams are deleted from `h2_connection.streams` - and this information is therefore not accessible anymore.

**Comment by Lukasa** [comment]
That seems like a reasonable API extension to me!

**Comment by Lukasa** [comment]
@Kriechi Is `get_next_available_stream_id` not sufficient for this?

**Comment by Kriechi** [comment]
I think this should be part of the API - otherwise I have to make sure my if condition is the same as in hyper-h2 each time something changes...

**Comment by Lukasa** [comment]
@Kriechi Let's step back a minute then: what is your expectation of the *use-case* for this feature?

**Comment by Kriechi** [comment]
I have multiple threads, each handling individual streams.
At some point I get a RstStream and hyper-h2 closes the stream.
Since the internal data structures regarding that stream might be cleaned up, I need to access the information if a stream was closed or is still active.

If it is closed, my thread needs to stop sending data (and all other frames) for that stream and quit.
If it is still active (non-closed) I can continue sending the next data frame.

**Comment by Lukasa** [comment]
So this problem is largely the result of the reset stream event popping on a separate thread to the data sending?

**Comment by Kriechi** [comment]
I guess so, yes. I'm open for alternative approaches!

**Comment by Lukasa** [comment]
Basically I'm trying to work out whether this is really hyper-h2's problem, or whether it's an application problem. I presume that the design you're working with has the code release the lock around the `H2Connection` object before you start processing the events, so that setting a flag is simply not good enough here, yes?

**Comment by Kriechi** [comment]
I guess you are right - I will debug it once more. Hopefully my problem vanishes.

**Comment by Lukasa** [comment]
To be clear @Kriechi, if this ends up being a really tricky problem to solve then we should add an API here to make it easier. I just want to make sure we solve the actual problem you have, rather than a hypothetical use-case. =)
