### ISSUE TITLE
Tolerate receiving frames on a closed stream

### ISSUE THREAD

**Issue by sethmlarson** [python-hyper/hyper-h2#1196]
We encountered this issue while running HTTPX against duckduckgo.com using HTTP/2:

https://github.com/encode/httpx/issues/173

Basically DDG would emit headers, data with end_stream=True, then emit a window update for that stream. h2 would error out on the window update because the stream is closed. Can h2 be changed to tolerate receiving non-response frames on a closed stream?

**Comment by sethmlarson** [comment]
Perhaps we should send `STREAM_CLOSED` on a `RST_STREAM` frame when this occurs?
https://httpwg.org/specs/rfc7540.html#StreamErrorHandler

**Comment by vmagamedov** [comment]
This was fixed in #1191

**Comment by vmagamedov** [comment]
@pgjones do you plan to make a new release soon?

**Comment by pgjones** [comment]
Dupe of #1183. 

Yep, hopefully Friday.

**Comment by sethmlarson** [comment]
Closing this as it's already been solved! Thank you everyone. :)
