### ISSUE TITLE
Tornado example implementation

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/hyper-h2#12]
Why leave Tornado out of the fun of example implementations?

**Comment by greencoder** [comment]
I'm really interested in helping on this one. My plan is to use Hyper in a Tornado-based Apple Push Notification Server once they release their HTTP/2-based protocol v3. (date unknown)

**Comment by Lukasa** [comment]
Nice! So, feel free to start playing around with the Twisted example and seeing how it might port to Tornado.

**Comment by akshatjain1995** [comment]
Can I get example of using flask, tornado and hyper together?

**Comment by Lukasa** [comment]
@akshatjain1995 Using hyper-h2 in what form? As a server? As a client?

**Comment by akshatjain1995** [comment]
@Lukasa As a server

**Comment by Lukasa** [comment]
See #304.

**Comment by akshatjain1995** [comment]
@Lukasa Thank you so much
