### ISSUE TITLE
Updates from [requires.io] are failing because pytest has dropped Python 2.7 support

### ISSUE THREAD

**Issue by alexwlchan** [python-hyper/hyper-h2#1202]
I went to investigate the failures from those emails; if you look in Travis you see the following error:

> Collecting pytest==5.1.3 (from -r /home/travis/build/python-hyper/hyper-h2/test_requirements.txt (line 1))
>
>  Could not find a version that satisfies the requirement pytest==5.1.3 (from -r /home/travis/build/python-hyper/hyper-h2/test_requirements.txt (line 1)) (from versions: 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.4.0, 2.4.1, 2.4.2, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.7.0, 2.7.1, 2.7.2, 2.7.3, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.9.0, 2.9.1, 2.9.2, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.0.6, 3.0.7, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.3.0, 3.3.1, 3.3.2, 3.4.0, 3.4.1, 3.4.2, 3.5.0, 3.5.1, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.6.4, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.8.0, 3.8.1, 3.8.2, 3.9.1, 3.9.2, 3.9.3, 3.10.0, 3.10.1, 4.0.0, 4.0.1, 4.0.2, 4.1.0, 4.1.1, 4.2.0, 4.2.1, 4.3.0, 4.3.1, 4.4.0, 4.4.1, 4.4.2, 4.5.0, 4.6.0, 4.6.1, 4.6.2, 4.6.3, 4.6.4, 4.6.5)
>
> No matching distribution found for pytest==5.1.3 (from -r /home/travis/build/python-hyper/hyper-h2/test_requirements.txt (line 1))

pytest dropped support for Python 2.7 [in their 5.x series](https://docs.pytest.org/en/latest/py27-py34-deprecation.html), thus this error.

**Comment by pgjones** [comment]
Hmm, I thought 25743dc855f6c15eb5a8ce3120c94dbec71a83a8 (and 0071a7ba7b55bdf71734be8435ed863ecaef9504) fixed this?

**Comment by alexwlchan** [comment]
I wonder if it’s not made it into those branches? I’ll try rebasing and see.

**Comment by pgjones** [comment]
Ah, that makes sense. Are we still maintaining those branches? Maybe we can mark them as closed?

**Comment by Kriechi** [comment]
I marked the branches as closed and removed them from requires.io.
