### ISSUE TITLE
Handle header values with whitespace pragmatically.

### ISSUE THREAD

**Issue by tomchristie** [python-hyper/hyper-h2#1206]
Raised via https://github.com/encode/httpx/issues/632

Currently header values with trailing whitespace are causing a ProtocolError to be raised. This is technically correct, but pragmatically it'd probably be a good idea for `hyper-h2` to handle the case, silently trimming the whitespace.

**Comment by vmagamedov** [comment]
Hi! Are you aware that you can control this behaviour using [H2Configuration](https://python-hyper.org/projects/h2/en/stable/api.html#h2.config.H2Configuration) -> `validate_inbound_headers`?

**Comment by tomchristie** [comment]
Ah fantastic, thanks!
