### ISSUE TITLE
Documentation: search result links are broken...

### ISSUE THREAD

**Issue by dimaqq** [python-hyper/hyper-h2#1216]
TL;DR The search results have links with extra `.rst` in them.

For example:
* go to https://python-hyper.org/projects/h2/en/stable/index.html
* search for "increment" in the search box
* you are sent to https://python-hyper.org/projects/h2/en/stable/search.html?q=increment&check_keywords=yes&area=default
* click the first result, "Advanced usage"
* you are taken to https://python-hyper.org/projects/h2/en/stable/advanced-usage.rst.html?highlight=increment which is a 404
* the correct link is https://python-hyper.org/projects/h2/en/stable/advanced-usage.html?highlight=increment

**Comment by Gallaecio** [comment]
The whole documentation seems broken at the moment.

**Comment by Lukasa** [comment]
Yeah, this feels like an RTD thing? Going directly to the RTD page (https://python-hyper.org/en/latest/) seems to get a 403. The 403 we see on python-hyper.org is just a reflection of the other one.

**Comment by sethmlarson** [comment]
I don't get a 403 for https://hyper-h2.readthedocs.io/en/latest/ though?

**Comment by Gallaecio** [comment]
Maybe the documentation link in the README is what is wrong?

**Comment by Lukasa** [comment]
I think it’s specifically the central page that is broken.

**Comment by vmagamedov** [comment]
@Lukasa I'm wondering how custom domain and SSL certificate is configured. There is an issue that you can't use Cloudflare to Cloudflare proxying: https://github.com/readthedocs/readthedocs.org/issues/4395 - many project with custom domains were affected. They even noted this issue in the docs: https://docs.readthedocs.io/en/stable/custom_domains.html. Maybe this is the reason?

**Comment by Kriechi** [comment]
This should be fixed now - please report any issues in a new ticket.
I updated a whole set of links and references - so search engines might take a while before they pick up the new correct URLs. The remaining broken links are fixed in the "lastest" docs, the "stable" docs are based on the most recent package release - so I'm planning a new release soon to also bump the docs.
