### ISSUE TITLE
Expand client examples

### ISSUE THREAD

**Issue by Molanda** [python-hyper/hyper-h2#1222]
Thank you for providing this framework.

I have adapted the Twisted `post_request.py` example as a Tornado client, which I am using to connect to the Apple Push Notification service.

However, the example is hard coded for a single stream and it is unclear how to properly process multiple streams of data with a client.

In the example, the connection is closed in `StreamEnded`.  This is probably not the correct place for this when using multiple streams.  Should the client also handle `ConnectionTerminated`?

The first stream's header and data is sent in `SettingsAcknowledged`.  If we want to keep this connection open and send additional streams with headers and data, where in the flow would that happen?

**Comment by Kriechi** [comment]
`StreamEnded` means that your request/response is complete (very high-level).
`ConnectionTerminated` is fired when the protocol either reported an error or the server closed the connection via a GoAway frame.

More streams (i.e., new requests) can be sent basically at any time with a call to `send_headers`. Then make sure to wait for the correct events from the server to receive your response headers and response body (and optionally trailers).

IMO providing detailed examples and workflows is a bit beyond the scope of this project. We do expect users to be familiar with the HTTP/2 protocol and its inner workings. If you simple need a HTTP client library to speak h2, I would recommend [httpx](https://www.python-httpx.org/http2/) or similiar projects.
