### ISSUE TITLE
Proxy not used when using hyper as an adapter in requests

### ISSUE THREAD

**Issue by txtsd** [python-hyper/hyper-h2#1224]
```python
import requests
from hyper.contrib import HTTP20Adapter
s = requests.session()
s.mount('https://httpbin.org', HTTP20Adapter())
s.proxies = {
     'http': 'http://192.168.1.2:8888/',
     'https': 'https://192.168.1.2:8888/'
}
s.get('https://httpbin.org/anything')
```

This sends a request, but it does not go through the defined proxy. Without the adapter, it does go through the proxy.

**Comment by vmagamedov** [comment]
Your issue probably should be submitted here: https://github.com/python-hyper/hyper

Also consider that [hyper](https://github.com/python-hyper/hyper) project is not actively maintained.

**Comment by txtsd** [comment]
I was under the impression it was the same project. My goal was to use http/2. Is there a way to do what I want with this project?

**Comment by vmagamedov** [comment]
You can use https://www.python-httpx.org project, which is using this library, and in active development. But `httpx` is in beta status and looks like they support http/2 only in async API.
