### ISSUE TITLE
ValueError: Stream ID must be non-zero

### ISSUE THREAD

**Issue by mhils** [python-hyper/hyper-h2#1231]
Caught this one while fuzzing @mitmproxy: `receive_data` raises a ValueError under specific circumstances, it should raise a ProtocolError instead.
```python
import h2.connection
conn = h2.connection.H2Connection()
conn.send_headers(1, [
    (':authority', 'example.com'),
    (':path', '/'),
    (':scheme', 'https'),
    (':method', 'GET'),
])
conn.reset_stream(1)
# the following raises ValueError: Stream ID must be non-zero
conn.receive_data(b'\x00\x00\x07\x05\x04\x00\x00\x00\x01\x00\x00\x00\x00\x84\x86\x82')  
```
([full traceback](https://gist.github.com/mhils/1fd3f5c9fde98253e0f0eb8a58dae907))

**Comment by Kriechi** [comment]
Just as note: This error bubbles up from hyperframe, which is correct.
I think we are just missing the h2 error wrapper here.
