### ISSUE TITLE
Related Projects?

### ISSUE THREAD

**Issue by akvadrako** [python-hyper/hyper-h2#1242]
Sorry if this is not appropriate for an issue, but I am wondering if there are any h2-based servers out there. For example, a complete HTTP server implementation.

If there are any known related projects, how about adding a section to the README, the wiki or the docs?

**Comment by sethmlarson** [comment]
This information is captured in the "used by" [section on GitHub](https://github.com/python-hyper/hyper-h2/network/dependents?package_id=UGFja2FnZS01MjE5MDQ4NQ%3D%3D), however if you'd like to create a section in the documentation that's more curated I'd accept that PR.

**Comment by pgjones** [comment]
[Hypercorn](https://gitlab.com/pgjones/hypercorn), [Twisted](https://github.com/twisted/twisted), and [Daphne](https://github.com/django/daphne) (built using Twisted) are the ones I know about.

**Comment by sethmlarson** [comment]
HTTPX as well

**Comment by akvadrako** [comment]
Thanks! PR created with these suggestions: https://github.com/python-hyper/hyper-h2/pull/1243
