### ISSUE TITLE
conn.close_connection() does not TCP connection

### ISSUE THREAD

**Issue by ganeshmurthy** [python-hyper/hyper-h2#1244]
The doc on the conn.close_connection() says - 
"Close a connection, emitting a GOAWAY frame."

When using wireshark, I see the GOAWAY frame being emitted but the TCP connection is not closed. Is this a known issue?

**Comment by sethmlarson** [comment]
Since this project doesn't use any TCP and is only a state machine for HTTP/2 I'm wondering if this is the project you meant to open this issue on?

If it is let me know and I'll reopen.
