### ISSUE TITLE
flow control impl is different from the RFC

### ISSUE THREAD

**Issue by boyxuper** [python-hyper/hyper-h2#137]
While trying to write a tornado http2 client with hyper-h2==2.0.0, nginx==1.9.10, 
H2Connection throws FlowControlError('May not increment flow control window past 2147483647',) after nginx sends two frame at the beginning:

1. SettingsFrame(Stream: 0; Flags: None):  {'body_len': 18, 'stream_id': 0, 'flags': , 'settings': {3: 4096, 4: 2147483647, 5: 16777215}}
2. WindowUpdateFrame(Stream: 0; Flags: None): 7fff0000 {'body_len': 4, 'stream_id': 0, 'flags': , 'window_increment': 2147418112}

The implementation was:
https://github.com/python-hyper/hyper-h2/blob/master/h2/connection.py#L846
which applies SETTINGS_INITIAL_WINDOW_SIZE to both connection and every each existing streams.

After reading the RFC, I found some points:
https://http2.github.io/http2-spec/#SETTINGS_INITIAL_WINDOW_SIZE

1. Both endpoints can adjust the initial window size for **new streams** by including a value for SETTINGS_INITIAL_WINDOW_SIZE in the SETTINGS frame that forms part of the connection preface. **The connection flow-control window can only be changed using WINDOW_UPDATE frames**.
1. A SETTINGS frame cannot alter the connection flow-control window.
1. SETTINGS frames always apply to a connection, never a single stream. The stream identifier for a SETTINGS frame MUST be zero (0x0).

And I think SETTINGS_INITIAL_WINDOW_SIZE should NOT applies to existing streams' window size, which should be updated only WINDOW_UPDATE frame.

**Comment by Lukasa** [comment]
Thanks for this @boyxuper!

So you're absolutely right that the settings frame needs to not apply to the connection, and that's what is causing the bug you're seeing here. However, the settings frame *does* change the window of active streams:

> When the value of SETTINGS_INITIAL_WINDOW_SIZE changes, a receiver MUST adjust the size of all stream flow-control windows it maintains by the difference between the new value and the only value.

So the only error here is that that change is being applied to the connection as well as the streams.

**Comment by boyxuper** [comment]
Thx for the fix @Lukasa

发自我的 iPad

在 2016-1-31，18:55，Cory Benfield <notifications@github.com> 写道：
