### ISSUE TITLE
Implement __repr__ for events

### ISSUE THREAD

**Issue by mhils** [python-hyper/hyper-h2#146]
We're currently debugging our mitmproxy http2 stuff - it would be very handy if the hyper-h2 events would have a human-readable `__repr__` that includes all their attributes.

@Lukasa, any chance to get that implemented? :smiley:

**Comment by Lukasa** [comment]
Yeah, sounds good to me. =)

**Comment by Lukasa** [comment]
Done. =)

**Comment by mhils** [comment]
Thanks so much for the insanely quick fix! :smiley: :cake:
