### ISSUE TITLE
Cannot install hyper-h2 on Ubuntu LTS

### ISSUE THREAD

**Issue by mhils** [python-hyper/hyper-h2#151]
Doing some tests for mitmproxy, I noticed that h2 doesn't install on either Ubuntu 12.04 or 14.04 by default: https://gist.github.com/mhils/d97ca425c33df644722f
We currently recommend mitmproxy users to just `pip install mitmproxy` in order to get a somewhat recent release - which doesn't work anymore with h2 as a dependency.

I know the whole thing sucks, but how can we address it best?

**Comment by Lukasa** [comment]
Urgh, LTS releases. @dstufft, got any suggestions?

**Comment by mhils** [comment]
Are there any public statistics from pypi regarding the pip/setuptools version distribution?

**Comment by sigmavirus24** [comment]
@Lukasa I think I have an idea of how to fix this if @mhils is willing to test it out for me. I'll send a PR shortly.

**Comment by mhils** [comment]
We have two distinct issues here:

- Ubuntu 12.04 - which picks up the source distribution by default - complains that 'extras_require' must be a dictionary
- Ubuntu 14.04 - which picks up the wheel by default - complains that `~=3.1` is not a version spec.

I'll try and build a wheel with `>=3.1, <4` and see if that fixes things for 14.04.

**Comment by sigmavirus24** [comment]
So #152 absolutely fixes the first item. The second item is a problem with LTS distributions doing fun things with pip and setuptools' vendored dependencies (and using ancient versions) that can't understand version syntax specified in PEPs that are a couple years old.

I strongly suspect not using the fancy `~=` will fix problem two.

**Comment by mhils** [comment]
FWIW:

| OS | pip | setuptools | wheel | `~=` | extras_require |
|---|---|---|---|---|---|
| Ubuntu 12.04 | 1.0 | 0.6 | / | no | no | 
| Ubuntu 14.04 | 1.5.4 | 3.3 | 0.24.0 | no | (to be determined) |

**Comment by sigmavirus24** [comment]
So I'm inclined to say anyone using anything older than pip 1.5 just shouldn't be supported. That version is both ancient enough and insecure enough to not be worth supporting.

**Comment by mhils** [comment]
#153 should address compatibility with 14.04. @dstufft, could we get some numbers on 12.04, before we drop support?

**Comment by dstufft** [comment]
<img width="264" alt="screen-shot-2016-02-05-09-32-16" src="https://cloud.githubusercontent.com/assets/145979/12849045/65885168-cbeb-11e5-99c0-975d86f7b6fb.png">

That's the top 32 things downloading from PyPI, ``null`` means we don't have that data available to us because of the version of the installer they used didn't include it in the information they send. The raw numbers are probably not the most important since it's over a few weeks, more important I'd suggest is to look at the relative magnitude of each number.

**Comment by mhils** [comment]
That sounds good enough - we'll just force those 12.04 users to upgrade pip, which they should do anyway. Thanks again everyone! :smiley:

refs mitmproxy/mitmproxy/pull/917
