### ISSUE TITLE
Better handling of streams after stream_reset

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/hyper-h2#157]
If the user resets a stream, it's possible there are still frames in flight that hyper-h2 may receive. Right now we handle this fairly ungracefully: let's improve it.

There are two key points:

1. We *must* process any HEADERS + CONTINUATION frames that come in, because those have affected the encoder/decoder state.
2. We *should* allow PRIORITY frames to proceed as normal.
3. We *must* allow DATA frames to affect the connection-level flow control window.
3. We *should* ignore all other frames.

I'm moderately flexible on (2), but let's do the other two well.

**Comment by Lukasa** [comment]
So the more general rule is that anything that affects connection-level state must take effect *first*. Then we need to check whether the stream is still present. If it isn't, and it was recently reset, then we want to ignore the frame.

However, after a sufficiently long time any further frame received is in error.

This is actually a tricky thing to time correctly, because there's no good 'rule of thumb' for how long to ignore frames for. We could say 30s, but it's easily possible to have network blips longer than 30s (GitHub had a documented network blip 90s long).

I'll have a play around and see if I can come up with a design I like.

**Comment by Kriechi** [comment]
This would also mean that we need outside information (timestamps from the socket) which is out of the control of hyper-h2. In doubt I would say the time in which we accept frames belonging to reset streams should be infinite.

**Comment by Lukasa** [comment]
> In doubt I would say the time in which we accept frames belonging to reset streams should be infinite.

Yeah, I think I'm leaning in that direction as well.

**Comment by Lukasa** [comment]
Urgh, just thought of a new weird edge case: technically a PUSH_PROMISE frame received after a RST_STREAM frame is sent still takes affect and reserves the stream. We'll need to account for that by ensuring that we issue RST_STREAM frames for any stream that is pushed to an already-reset stream.

**Comment by Lukasa** [comment]
So issue (2) will be tackled as #168, I think. This issue concerns itself primarily with 1, 3, and 4.
