### ISSUE TITLE
client_side argument for H2Connection is undocumented

### ISSUE THREAD

**Issue by brettcannon** [python-hyper/hyper-h2#160]
The examples seem to use `False` but the default argument is `True`. I suspect it means client vs. server and there simply isn't any client-side example code (yet).

**Comment by Lukasa** [comment]
Ah, there is some client-side example code in the docs [here](http://python-hyper.org/h2/en/stable/examples.html#example-clients). However, good spot that `client_side` is undocumented. I'll add that today.
