### ISSUE TITLE
Document why 65,535 is used for the amount of data to read from a socket

### ISSUE THREAD

**Issue by brettcannon** [python-hyper/hyper-h2#161]
I realize the number is what can fit in a 16-bit number, but there's comment saying if that's some magical HTTP/2 value or just what you prefer to read from a socket at a time. And if it is somehow magical to HTTP/2 (e.g., packet size or something), then that should probably be part of the API. Otherwise a quick comment that it's not magical would be handy for those of us who don't write networking code constantly.

**Comment by Lukasa** [comment]
To be clear, we're talking about the example on [this page in the documentation](http://python-hyper.org/h2/en/stable/basic-usage.html)?

**Comment by Kriechi** [comment]
It not a magical thing (AFAIK). In mitmproxy we read always complete frames from the socket and pass it on to h2 - a lot easier to debug when you can inspect each frame as it enters the h2-connection.
Take a look here for an example: https://github.com/mitmproxy/netlib/blob/1af231fe01350d056f3b6c14a695caf9eadda520/netlib/utils.py#L402-L416

**Comment by Lukasa** [comment]
So while @Kriechi is right that 65535 is not magical, in the case of the example documentation it's still arbitrary. There's no requirement to use it, it's just a sensible upper bound on the amount of data a user is likely to want to process at once.

**Comment by brettcannon** [comment]
So you're right about the page that you referenced, @Lukasa , but it's also used in the [curio example](http://python-hyper.org/h2/en/stable/curio-example.html).

**Comment by Lukasa** [comment]
Ah good spot, let's fix that up too.
