### ISSUE TITLE
How are new releases formed?

### ISSUE THREAD

**Issue by etataurov** [python-hyper/hyper-h2#175]
I found it a bit unclear what changes will go to the next release.
The 2.1.x branch has 29 commits ahead and 59 commit behind master.
What changes go from master to 2.1.x branch?

Thanks 🙂

**Comment by Lukasa** [comment]
@etataurov Yeah, we may want a document for this. Essentially, all changes are merged to the master branch. Then, anything that amounts to a bugfix change is backported to the 2.1.X branch via a git cherry-pick. The 2.1.X branch is currently at the v2.1.2 tag, so there are no changes in there that aren't in 2.1.2. Thus, the current state of the changelog on master shows all changes that have not been backported to 2.1.X.

**Comment by etataurov** [comment]
@Lukasa thanks for clarifying.

**Comment by Lukasa** [comment]
@etataurov Yeah, sorry about how messy that is, but it represents me doing my level best to maintain patch releases for longer periods of time while still allowing forward progress on the API. I'll write up a policy for how long I'll keep each minor release alive and how I handle backporting changes.

It's a bit rough that Git doesn't have a better policy for this, but given the way Git keeps track of a revision we can't merge it into multiple branches in any kind of clean way.
