### ISSUE TITLE
Document more examples beyond simple GET

### ISSUE THREAD

**Issue by kdart** [python-hyper/hyper-h2#180]
Could use some more advanced examples.  Specifically, how to read the body of a POST message as a server. Is there any currently available code or example for this?

Also, the website documentation (RTD) doesn't reflect the current API. The source documentation is OK. Should just be a matter of pushing it out there.

**Comment by Lukasa** [comment]
Thanks for this!

Agreed, an example of how to read a POST is a good idea. Currently there is no example code, but it should be easy enough for me to write some today.

As for RTD, the RTD docs are currently defaulted to `stable`, which means that the docs are shown for the most recent version available from PyPI (v2.1.2). This is deliberate: the vast majority of programmers will use the most recent release from PyPI rather than work from master. We have some very minor API changes in the `master` branch, but I don't believe anything that has been released is missing from the v2.1.2 docs on RTD. Am I wrong about that?

**Comment by kdart** [comment]
Cool, thanks.

About RTD, I think I got a little confused by there being actually two sites.

http://python-hyper.org/h2/en/stable/
http://hyper.readthedocs.org/en/latest/

That last one is for a version much older than the PyPI one.

**Comment by kdart** [comment]
There's something else I ran into. I'm also writing a simple WSGI adapter based on the curio example code. But the WSGI environ requires a stream, or file-like object to read from (the 'wsgi.input' entry).
. I'm not sure how to map that to the HTTP2 protocol. The original method of using the makefile method on the socket ('wsgi.input':  sock.makefile("rb", 32758),) won't work, I'm pretty sure. I'm thinking I'll need an adapter to to mock a file-like object for the WSGI app. What do you think?

**Comment by Lukasa** [comment]
@kdart So, for RTD, the other one is actually for an altogether different library! That library is still under active development (by me), and has an unfortunately fairly similar name. At some point I'll fold it in to the current docs location, but for now it lives separately.

For WSGI: yeah, so this is a great point, and I suspect the "write a WSGI adapter" problem might make a good "advanced worked problem" (as a follow-on from the [basic worked problem](http://python-hyper.org/h2/en/stable/basic-usage.html) in the docs).

So the way to get your file-like object is to essentially wrap a buffer or a queue. In one logical thread of execution you process your connection, pulling data off the socket and passing it to the `H2Connection` object. In the logical thread of execution processing the WSGI application, you have a class that owns a queue and exposes the various methods required of WSGI.

The `read` method then uses the queue as its source of data. You essentially have two concurrent loops. One looks like this:

```python
while True:
    data = sock.recv(8192)
    events = conn.receive_data(data)
    for event in events:
        if isinstance(event, h2.events.RequestReceived):
            # Do WSGI stuff
        elif isinstance(event, h2.events.DataReceived):
            # Put the data in the queue for the given stream
```

The other then has (I'm missing code to handle the `amt=None` case, but you can work that out yourself):

```
def read(amt):
    data = b''
    while len(data) < amt:
        data += queue.pop()
    return data
```

The other thing that `read` function would need to do is store excess data, but that's not too difficult either.

**Comment by defnull** [comment]
It really gets interesting if you want to use HTTP2 flow control to stop the client from sending data if the queue (let's call it buffer) grows to large. I have that exact use case. An advanced example would be great!

**Comment by Lukasa** [comment]
@defnull That's actually not that hard to do *at all*, so I'm happy to work that into the example. It'll also be a useful place to talk about HTTP/2 flow control in a narrative documentation context, which I haven't previously done in the docs (so the only example of what to do is literally *in* code examples, making it a bit tricky).

**Comment by Lukasa** [comment]
See #181 for an example of a HTTP/2-only WSGI server.

**Comment by kdart** [comment]
Thanks for all your effort!
