### ISSUE TITLE
Remove deprecated fallback for dictionaries as headers.

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/hyper-h2#183]
Remove the fallback that was deprecated in #184.

**Comment by LuRsT** [comment]
Can anyone review this change please?

**Comment by Lukasa** [comment]
@LuRsT This change looks good to me: however, there's currently no roadmap for the 3.0.0 release (it'll be released when we have other breaking changes).

You're welcome to open a PR with this change but it won't get merged until we're ready to go, so it'll likely drift from the current master pretty painfully over time. So instead, I recommend posting that patch in this issue (the output from `git diff`) will be fine, so that the patch doesn't get lost. =)

**Comment by LuRsT** [comment]
Sure thing, also, part of what I did in that commit (changing the dict headers in the test) should be merged to avoid confusion right (if yes, I'll send a PR with just that change, if not, I'll keep it here with the rest)?

**Comment by Lukasa** [comment]
@LuRsT How about we go one step further. Can you make the dict headers change, but also add a *new* test that explicitly tests that dicts are accepted? That gives us a single targetted test that can also be removed along with this change.

**Comment by LuRsT** [comment]
@Lukasa Of course! Great idea, will do that!

**Comment by LuRsT** [comment]
@Lukasa done, could you check if that's what you wanted?

**Comment by Lukasa** [comment]
\o/ Fab!

**Comment by Lukasa** [comment]
This is happening in #500.
