### ISSUE TITLE
Server POST examples

### ISSUE THREAD

**Issue by 130security** [python-hyper/hyper-h2#222]
Probably not the best place for it but, hey I wanted to say: great work!
I was also curious if you've had the time to put together some additional server examples dealing with other methods (POST, etc.)?

**Comment by Lukasa** [comment]
@130security Yeah, absolutely, and this feels like a good idea. I'll tag this as 'easy' to see if any of @python-hyper/contributors want to take a swing at this, but I'll also take a look sometime today.

**Comment by Lukasa** [comment]
@130security Out of interest, what specifically are you looking for? The asyncio WSGI server example handles POST requests because it's a full-blown WSGI server, but I appreciate that it may be a bit more complex than you want, so what specific function do you want clarified?

**Comment by 130security** [comment]
Awesome! Yes, WSGI may be a bit too involved for me just yet, specifically since Python is not my native language (literally started playing with with it last week). 
I actually looked at your Twisted example last night, which handles GET, played around with it and with minor tweaking was able to adapt it for POST-ing a JSON by passing "data" to dataFrameReceived and pulling the JSON within it with json.loads(data). Fun but I'm not sure if this is the sexier way to do it, so any simple example demonstrating it would be greatly appreciated! :)

**Comment by Lukasa** [comment]
@130security That's very close to the right thing to do! The key thing to be aware of is that you may get multiple data frames before the response is complete, so you'd normally want to buffer until StreamEnded is received. I'll aim to provide an updated example sometime today.
