### ISSUE TITLE
Links to docs broken

### ISSUE THREAD

**Issue by tomviner** [python-hyper/hyper-h2#239]
The header link on github, and the link in the readme point to http://python-hyper.org/h2/ which 404s.

**Comment by Lukasa** [comment]
Yeah, this is something I'm aware of. It's problematic, but it's tied to rtfd/readthedocs.org#2235, which would need to be fixed. It's literally the project root that doesn't work though: all the other links work.

I'm conflicted about undoing this: I'd rather see the bug for readthedocs fixed. =(

**Comment by tomviner** [comment]
Ah I see, fair enough.

**Comment by Lukasa** [comment]
*Ideally*, if @ericholscher wants to make good use of resources, he'd point me at where in the readthedocs.org stack this problem is likely to be occurring and I'd go digging to try to fix it. =P

**Comment by ericholscher** [comment]
Sadly this is part of our ops infrastructure, which isn't open sourced because it has lots of secrets and API keys, etc. I'll try and get it resolved here soon.

**Comment by ericholscher** [comment]
Alright, this should now be fixed if you use the `/projects/h2/` URL structure.

**Comment by Lukasa** [comment]
Yup, resolved. Thanks so much @ericholscher! ❤️❤️❤️

**Comment by tomviner** [comment]
Thanks @ericholscher and @Lukasa :-)
