### ISSUE TITLE
PROTOCOL_ERROR is occured when I use H2

### ISSUE THREAD

**Issue by NetWilliam** [python-hyper/hyper-h2#247]
I want to use h2 as client to send request to apns, howerver I have met this problem in stumble test, 
my python ssl context configure as follow:
```
    ctx = ssl.create_default_context()
    ctx.options |= (ssl.OP_NO_TLSv1 | ssl.OP_NO_TLSv1_1 | ssl.OP_NO_COMPRESSION)
    ctx.set_ciphers('ECDHE+AESGCM')
    ctx.load_cert_chain(APNS_CERT)
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    ctx.set_alpn_protocols(['h2'])
```

here is debug log of mock server written by go:

2016/06/23 16:12:11 http2: server connection from 127.0.0.1:51079 on 0xc820016100
2016/06/23 16:12:11 http2: Framer 0xc82034a210: wrote SETTINGS len=18, settings: MAX_FRAME_SIZE=1048576, MAX_CONCURRENT_STREAMS=250, MAX_HEADER_LIST_SIZE=1048896
2016/06/23 16:12:11 http2: server: client 127.0.0.1:51079 said hello
2016/06/23 16:12:11 http2: Framer 0xc82034a210: read SETTINGS len=30, settings: HEADER_TABLE_SIZE=4096, ENABLE_PUSH=1, MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=65535, MAX_FRAME_SIZE=16384
2016/06/23 16:12:11 http2: server read frame SETTINGS len=30, settings: HEADER_TABLE_SIZE=4096, ENABLE_PUSH=1, MAX_CONCURRENT_STREAMS=100, INITIAL_WINDOW_SIZE=65535, MAX_FRAME_SIZE=16384
2016/06/23 16:12:11 http2: server processing setting [HEADER_TABLE_SIZE = 4096]
2016/06/23 16:12:11 http2: server processing setting [ENABLE_PUSH = 1]
2016/06/23 16:12:11 http2: server processing setting [MAX_CONCURRENT_STREAMS = 100]
2016/06/23 16:12:11 http2: server processing setting [INITIAL_WINDOW_SIZE = 65535]
2016/06/23 16:12:11 http2: server processing setting [MAX_FRAME_SIZE = 16384]
2016/06/23 16:12:11 http2: Framer 0xc82034a210: read SETTINGS flags=ACK len=0
2016/06/23 16:12:11 http2: server read frame SETTINGS flags=ACK len=0
2016/06/23 16:12:11 http2: Framer 0xc82034a210: read WINDOW_UPDATE len=4 (conn) incr=2147418112
2016/06/23 16:12:11 http2: server read frame WINDOW_UPDATE len=4 (conn) incr=2147418112
2016/06/23 16:12:11 http2: Framer 0xc82034a210: wrote SETTINGS flags=ACK len=0

2016/06/23 16:12:15 http2: Framer 0xc82034a210: read HEADERS flags=END_HEADERS stream=1 len=20
2016/06/23 16:12:15 http2: server read frame HEADERS flags=END_HEADERS stream=1 len=20
2016/06/23 16:12:15 http2: server decoded header field ":method" = "POST"
2016/06/23 16:12:15 http2: server decoded header field ":path" = "/"
2016/06/23 16:12:15 http2: server decoded header field "apns-topic" = "nonthingbig"
2016/06/23 16:12:15 http2: Framer 0xc82034a210: read DATA flags=END_STREAM stream=1 len=163 data="{\"r\": \"test-task-id\", \"l\": \"\", \"aps\": {\"badge\": 0, \"alert\": {\"body\": \"\u6709\u591a\u4e45\u6ca1\u4e0b\u53a8\u623f\u4e86\uff1f\", \"title\": null}, \"sound\": \"default\"}}"
2016/06/23 16:12:15 http2: server read frame DATA flags=END_STREAM stream=1 len=163 data="{\"r\": \"test-task-id\", \"l\": \"\", \"aps\": {\"badge\": 0, \"alert\": {\"body\": \"\u6709\u591a\u4e45\u6ca1\u4e0b\u53a8\u623f\u4e86\uff1f\", \"title\": null}, \"sound\": \"default\"}}"
2016/06/23 16:12:15 http2: Framer 0xc82034a210: wrote RST_STREAM stream=1 len=4 ErrCode=**PROTOCOL_ERROR**
2016/06/23 16:12:15 http2: Framer 0xc82034a210: wrote RST_STREAM stream=1 len=4 ErrCode=**STREAM_CLOSED**

**Comment by NetWilliam** [comment]
is there any mistakes i make and i am still not knowing about?

**Comment by Lukasa** [comment]
@NetWilliam Interesting. It seems like the Go server doesn't like the HTTP/2 we're sending here. Is it possible for you to provide some more details about how your Go server is configured, what your client code looks like, and ideally a packet capture of the decrypted traffic?

At the first instance though, with just the logs you've got here, I'd suggest that it's possible you're missing some header fields. You've provided `:method` and `:path`, but a HTTP/2 request should also provide `:authority` and `:scheme`. Do you want to try to add those two? `:authority` should contain the hostname of the server, and `:scheme` should be `https`.

**Comment by NetWilliam** [comment]
bingo!! it is `:authority` and `:scheme` that all i need to build a successful connection 😃  thank you

**Comment by Lukasa** [comment]
My pleasure, glad to be of some assistance!
