### ISSUE TITLE
Support sending memoryview objects in DATA frames.

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/hyper-h2#250]
Encountered this as part of working on Twisted's HTTP/2 client.

When writing large amounts of data in a non-prioritised way (like a client would!), it's entirely possible that a stack will want to send > SETTINGS_MAX_FRAME_SIZE data in one go. This will require that the stack split the write up into multiple chunks. For large single writes or small values of SETTINGS_MAX_FRAME_SIZE this represents quite a lot of copying, which is substantially less than ideal.

It would be better, then, if we could support `memoryview` objects in DATA frames for as long as possible before concretizing to bytes. This may require some additional support in hyperframe, as ideally we'd only concretize the memoryview when we serialize the frame.

An alternative is to allow the `send_data` call to automatically chunkify your writes. That would let the `memoryview` use be entirely internal. I'm inclined not to want to do that, but it's worth noting that the option exists.

**Comment by fredthomsen** [comment]
I am interested in this and looking at the code seems like this is still outstanding.  I'll start looking into this.

**Comment by fredthomsen** [comment]
To avoid this unnecessary copying, it seems the the `DataFrame` would need to have a member variable which was a `memoryview` object. However, it seems that that runs counter to statement you made above in terms of delaying the conversion to the `memoryview` until the frame is serialized:

> This may require some additional support in hyperframe, as ideally we'd only concretize the memoryview when we serialize the frame.

**Comment by fredthomsen** [comment]
@Lukasa also you mention that you would prefer `memoryview` use to be external rather than internal; however, why not both?  I understand your preference for internal over external.  If a `memoryview` instance is passed in, then great, the user is handling it as they should; however, would you not also want the ability to do some buffering internally converting a `bytes` object to a `memoryview` then creating as many `DataFrame` s as necessary?

**Comment by Lukasa** [comment]
No, sorry: "concretize" means "convert to bytes". We're in agreement. 

As to the other stuff: it may be worth doing. But memoryview objects aren't free to create, so we may not be able to come up with a good heuristic for when to use them and when not to. Hard to be sure. So my instinct is to solve one problem at a time.

**Comment by fredthomsen** [comment]
Ok, I misread and am on the same page now; keep things as a `memoryview` as long as possible.

In terms of the cost of a `memoryview`, I don't follow.  I understand they are not free; however, they certainly are cheaper than the repeated copying of `bytes`.

**Comment by Lukasa** [comment]
Yes, but for small numbers of copies not by much. And they're more than not copying at all, which can happen if the data chunk is appropriately sized for the connection.

**Comment by Lukasa** [comment]
Ok, the necessary hyperframe work has been merged.
