### ISSUE TITLE
hyper-h2 content length tracking doesn't work with HEAD requests

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/hyper-h2#255]
Responses to HEAD requests may have a Content-Length header that corresponds to what their body *would* be, but provide no body. Our content-length tracking doesn't respect that. We should fix it!

See also: #254.

**Comment by aidylewis** [comment]
Would this exception only be thrown with a HEAD request? Could we not extract the request method and add it to this conditional? 
https://github.com/python-hyper/hyper-h2/blob/master/h2/stream.py#L1082

**Comment by Lukasa** [comment]
@aidylewis We absolutely could, though in practice I think we should do the initialization properly instead (initialize the expected length to zero, don't bother looking for the actual `Content-Length` header.

**Comment by aidylewis** [comment]
@Lukasa That would mean deleting the _track_content_length method and all references to it. All it does is compare expected with actual.

**Comment by Lukasa** [comment]
No, we can use `_track_content_length`. `_track_content_length` works in tandem with `_initialize_content_length`, right above it. I'm suggesting that `_initialize_content_length` should have a new branch in it that, based on request method, forces `_expected_content_length` to `0` if it's a `HEAD` request.

**Comment by aidylewis** [comment]
Would would be the best way to extract the request method?

**Comment by Lukasa** [comment]
It'll have to be searched out of the request headers when they're sent. Probably in `send_headers`.

**Comment by Lukasa** [comment]
Resolved by #264 via #258. Thanks @aidylewis!
