### ISSUE TITLE
It’s possible to send header blocks from hyper-as-server that hyper-as-client will reject

### ISSUE THREAD

**Issue by alexwlchan** [python-hyper/hyper-h2#262]
Picking up a comment from #261:

We do a series of checks in the `validate_headers` pipeline for incoming header blocks, in particular:

- [x] All fields should be lowercase.
- [x] A Transfer-Encoding header must have value "trailers"
- [x] No blocks with the Connection header.
- [x] No duplicate pseudo-header fields and/or pseudo-header fields coming after an ordinary header field.
- [x] No header blocks with bad :authority/Host headers.

But we don’t enforce all these rules on header blocks that we send, which suggests that it’s possible to send a header block with hyper that we’d reject if we received. Which seems odd.

(1) is achieved by the `_lowercase_header_names` pipeline, and I’m adding (5) in #261. I think we should be enforcing (2)-(4) on header blocks that we send as well.

Does that seem sensible?

**Comment by Lukasa** [comment]
I've updated the original comment to turn the list into a list of checkboxes so we can keep track. Feel free to tackle each one separately.

**Comment by alexwlchan** [comment]
Note: if you’re going to tackle this, you should read the discussion on #246 about being able to skip these checks in certain cases.

**Comment by alexwlchan** [comment]
All addressed in #289.
