### ISSUE TITLE
Does hyper reject trailers that contain pseudo-header fields?

### ISSUE THREAD

**Issue by alexwlchan** [python-hyper/hyper-h2#263]
Spotted in [RFC 7540 section 8.1.2.1](https://tools.ietf.org/html/rfc7540#section-8.1.2):

> Pseudo-header fields MUST NOT appear in trailers.

Does hyper enforce this rule? Should it?

I’d expect this rule to be enforced in the `validate_headers()` pipeline, but that’s only just learnt how to distinguish between trailers and non-trailers, so I don’t think it would have been able to enforce this rule.

**Comment by Lukasa** [comment]
That's easily checked: write a test, see what happens!

**Comment by nateprewitt** [comment]
It looks like this may have been patched in #289?

**Comment by Lukasa** [comment]
I don't know that anyone actually wrote a test for this. @nateprewitt, want to contribute a test for this specific case so that we can really consider this closed?

**Comment by nateprewitt** [comment]
Sure, I'd be happy to give it a go.

**Comment by alexwlchan** [comment]
I’m not sure #289 does address this. At least, I can’t see it at a quick glance of the code, and I don’t remember writing anything to explicitly cover this case (test or otherwise).

**Comment by Lukasa** [comment]
Resolved by #305.

**Comment by alexwlchan** [comment]
@Lukasa Err, is this resolved or not?

**Comment by Lukasa** [comment]
Yes. I have got exactly no idea why this exploded everywhere.
