### ISSUE TITLE
Reject header fields with invalid whitespace characters.

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/hyper-h2#271]
Relevant: golang/go#16572.

We should forbid implementations from emitting header fields with invalid whitespace characters. Generally, that means surrounding whitespace of any kind, either leading or trailing, from both header field names and header field values.

**Comment by alexwlchan** [comment]
Is there anything left to do, or is this fixed by #281?

**Comment by Lukasa** [comment]
I think this is fixed by #281.
