### ISSUE TITLE
Branch mismatch in docs

### ISSUE THREAD

**Issue by kracekumar** [python-hyper/hyper-h2#278]
The documentation [step 6](http://hyper.readthedocs.io/en/development/contributing.html#steps) specifies `Send a GitHub Pull Request to the main repository’s development branch.`. Unfortunately `development` directory is missing. Should it say as `Send a GitHub Pull Request to the main repository’s master branch`?

**Comment by Lukasa** [comment]
Confusingly (and this is totally my fault), that documentation is actually for a different project. This is covered by the docs at http://python-hyper.org/

**Comment by kracekumar** [comment]
The link to contribution docs from README.md is leading to the wrong place, and I will replace with http://python-hyper.org/en/latest/contributing.html?

**Comment by Lukasa** [comment]
Yes please! =)
