### ISSUE TITLE
POST request of 64K and above

### ISSUE THREAD

**Issue by kashirin-alex** [python-hyper/hyper-h2#288]
A post request go idle after 64k-1 bytes received 
-- with opera it is 24 (2Kb+) events
-- IE it is 4 (16Kb) events
The settings are acknowledged while seems to be not used.
Setting of highest values at connection start with self.conn.update_settings does not help. 

here are the events output of a request with opera:
`
<RemoteSettingsChanged changed_settings:{3: ChangedSetting(setting=3, original_value=None, new_value=1000), 4: ChangedSetting(setting=4, original_value=65535, new_value=6291456)}>
<WindowUpdated stream_id:0, delta:15663105>
<RequestReceived stream_id:1, headers:[(':method', 'POST'), (':authority', 'thither.direct'), (':scheme', 'https'), (':path', '/component/administration/saveform/cms/files/modify_cms_file'), ('content-length', '480438'), ('cache-control', 'max-age=0'), ('origin', 'https://thither.direct'), ('upgrade-insecure-requests', '1'), ('user-agent', 'Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36 OPR/39.0.2256.48'), ('content-type', 'multipart/form-data; boundary=----WebKitFormBoundaryIaq0FT3vVtOmXti3'), ('accept', 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8'), ('referer', 'https://thither.direct/component/administration/details/cms/files/modify_cms_file/?CMSfilePathName=/material/assets/css/:components.css'), ('accept-encoding', 'gzip, deflate, lzma, br'), ('accept-language', 'en-US,en;q=0.8'), ('cookie', 'TD-adm=122331657601169140331')]>
<PriorityUpdated stream_id:1, weight:256, depends_on:0, exclusive:True>
<DataReceived stream_id:1, flow_controlled_length:2852, data:2d2d2d2d2d2d5765624b6974466f726d426f756e>
1 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:5f66696c656c697374206c692c0d0a2e70617373>
2 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:61722d6d6f62696c652d6465746163686564202e>
3 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:6d6174657269616c2d636f6e74656e74203e2073>
4 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:676174696f6e2d64697669646572207b0d0a2020>
5 : 2852
<DataReceived stream_id:1, flow_controlled_length:2124, data:6c74202e6e617669676174696f6e206c69203e20>
6 : 2124
<DataReceived stream_id:1, flow_controlled_length:2852, data:6c67203e206c69203e2061203e207370616e207b>
7 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:202e736964656261722d64657461636865642e61>
8 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:7465723b0d0a2020202070616464696e672d6c65>
9 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:20746f703a20303b0d0a2020202070616464696e>
10 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:723a6e6f74282e736964656261722d6465666175>
11 : 2852
<DataReceived stream_id:1, flow_controlled_length:2124, data:61756c74202e6e61762d6a757374696669656420>
12 : 2124
<DataReceived stream_id:1, flow_controlled_length:2852, data:61796f75742d626f786564203e202e6e61766261>
13 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:2d7472616e73666f726d3a20726f746174652833>
14 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:3b0d0a2020626f726465722d636f6c6f723a2023>
15 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:6e652d6865696768743a20313b0d0a2020626f72>
16 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:6e2d6f757420696e66696e6974653b0d0a20202d>
17 : 2852
<DataReceived stream_id:1, flow_controlled_length:2124, data:0a20206865696768743a20333070783b0d0a2020>
18 : 2124
<DataReceived stream_id:1, flow_controlled_length:2852, data:656c61746976653b0d0a202077696474683a2032>
19 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:7075745b747970653d636865636b626f785d207b>
20 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:74697665202e63686f696365207370616e3a6166>
21 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:697a653a20313470783b0d0a20206c696e652d68>
22 : 2852
<DataReceived stream_id:1, flow_controlled_length:2852, data:363470783b0d0a7d0d0a2e636865636b626f782d>
23 : 2852
<DataReceived stream_id:1, flow_controlled_length:2123, data:2c0d0a2e626f6f7473747261702d737769746368>
24 : 2123
<SettingsAcknowledged changed_settings:{3: ChangedSetting(setting=3, original_value=100, new_value=128)}>
<SettingsAcknowledged changed_settings:{}>
`

**Comment by Lukasa** [comment]
As you read and process data, you need to update the flow control window for both the connection and the stream. Specifically, you need to call [this](http://python-hyper.org/projects/h2/en/stable/api.html#h2.connection.H2Connection.increment_flow_control_window) method twice: once with `stream_id` equal to whatever stream you're processing (`1` in this case), and once with no `stream_id`. You need to pass `DataReceived.flow_controlled_length` as the increment.

**Comment by evilaliv3** [comment]
@Lukasa : do you think this might have any relation with https://github.com/globaleaks/globaleaks-whistleblowing-software/issues/4841 ? 

Thank you!
