### ISSUE TITLE
Lookup meaningful name for error code

### ISSUE THREAD

**Issue by Kriechi** [python-hyper/hyper-h2#295]
Right now `h2.error.H2_ERRORS` only is a list of all error codes as raw values.
It would be nice to lookup a meaningful name for a given error code.

E.g.: 
```
>>> some_error_code_value = 0x7
>>> h2.ErrorCodes.get_name(some_error_code_value)
'REFUSED_STREAM'
```

This would allow us to generate more meaningful error messages and debug output.

**Comment by Lukasa** [comment]
I wonder if we shouldn't turn these into an Enum. We could still expose their names as individual values as we currently do for back compatibility, but deprecate them in favour of the enum in 3.0.

**Comment by Kriechi** [comment]
Yes, Enum sounds like a good plan. 👍
