### ISSUE TITLE
Design Patterns Documentation

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/hyper-h2#30]
It would be interesting to see the documentation dive into suggested design patterns when using Hyper-h2. These are potentially quite educational in general, in addition to providing more insight into how Hyper-h2 works. See [this comment](https://github.com/python-hyper/hyper-h2/commit/7c1273f6244db95aaf702cf387321853bf94cc97#commitcomment-13705781) for more discussion.

**Comment by Mec-iS** [comment]
I am taking time to define a starting schema to write this kind of documentation starting from:

> So, on the topic of "a server you can use with your browser", that turns out to be A Pain In The Ass™. The security requirements for HTTP/2 are high, which means you need a quite recent OpenSSL. Both the Twisted example and the asyncio example can do it (the Twisted one requires a Twisted patch that I haven't landed yet), but in both cases you need OpenSSL 1.0.2 or newer, which is comparatively rare.

> I think it's worth documenting these requirements and what you do once you've satisfied them though.

> Got suggestions for design patterns worth seeing? I can think of a few:

> -     coroutines, using asyncio
> -     event-driven, using Twisted
> -     no-shared-memory threading
> -     shared-memory threading (one threading example could use actual threads, the other could use gevent/eventlet)

> Suggestions for more would be great.

**Comment by aidylewis** [comment]
Would it be an idea to provide an example using Python's 3.5.X async/await?

**Comment by Lukasa** [comment]
@aidylewis I believe we have two already in the examples directory, but more is always better!
