### ISSUE TITLE
Unexpected GOAWAY encountered when doing early prioritization of some sites.

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/hyper-h2#302]
When using hyper-h2 to perform early stream prioritization, some sites break entirely. Specifically, if hyper-h2 is used to send a PRIORITY frame on stream 1, and then a HEADERS frame on stream 1, the following sites issue a `GOAWAY(error_code=STREAM_CLOSED, additional_data="invalid stream id in HEADERS frame")`:

- https://python.org
- https://h2o.examp1e.net/

My understanding of RFC 7540 is that PRIORITY frames do not change stream state. *Certainly* they do not transition the stream state to closed, meaning that STREAM_CLOSED would be an invalid error code.

In the case of python.org, they're behind Fastly, so I'd like to ping @dstufft to get the ball rolling there. Feel free to refer a relevant Fastly engineer to this issue for follow-up @dstufft. In the case of h2o.examp1e.net I don't know if there's a CDN there or not, but certainly the server itself belongs to @kazuho so I'll ping him in the first instance.

This was found by @Kriechi in the mitmproxy team as part of mitmproxy/mitmproxy#1498.

The repro script is below (requires `pip install h2 certifi` to run):

```python
#!/usr/bin/env python2
 
import certifi
import h2.connection
import h2.events
 
import errno
import socket
import ssl
import time

SERVER_NAME = 'www.python.org'
 
socket.setdefaulttimeout(2)
 
c = h2.connection.H2Connection()
c.initiate_connection()
 
ctx = ssl.create_default_context(cafile=certifi.where())
ctx.set_alpn_protocols(['h2', 'http/1.1'])
ctx.set_npn_protocols(['h2', 'http/1.1'])
 
s = socket.create_connection((SERVER_NAME, 443))
s = ctx.wrap_socket(s, server_hostname=SERVER_NAME)
 
s.sendall(c.data_to_send())
 
c.prioritize(1, weight=201, depends_on=0, exclusive=False)
 
headers = [
    (':method', 'GET'),
    (':path', '/'),
    (':authority', SERVER_NAME),
    (':scheme', 'https'),
    ('user-agent', 'custom-python-script'),
]
c.send_headers(1, headers, end_stream=True)
 
s.sendall(c.data_to_send())
 
 
while True:
    data = s.recv(65536 * 256)
    if not data:
        break
 
    try:
        events = c.receive_data(data)
        s.sendall(c.data_to_send())
    except:
        break
 
    for event in events:
        if isinstance(event, h2.events.DataReceived):
            print "Received %d bytes of data" % event.flow_controlled_length
        elif isinstance(event, h2.events.ConnectionTerminated):
            print "GOAWAY", event
            break
```

**Comment by deweerdt** [comment]
@Lukasa thank you for reporting the issue and the repro case. I've submitted a tentative fix for H2O.

**Comment by Lukasa** [comment]
@deweerdt Our pleasure, thanks for submitting a fix to H2O!

**Comment by Lukasa** [comment]
Ok, it appears that the known broken implementations here are based on the same codebase, so with the fix in h2o/h2o#1043 merged I think we can call this fixed. Thanks all!

**Comment by kazuho** [comment]
Out of curiosity, may I ask why hyper sends a `PRIORITY` frame separate from `HEADERS` (instead of using the `PRIORITY` flag of the `HEADERS` frame)?

**Comment by Kriechi** [comment]
This is actually a behaviour in Firefox - which sends a few PRIORITY frames at the beginning of each frame. And then a new stream might trigger this error if the stream id was equal to the last PRIORITY information update.

**Comment by kazuho** [comment]
@Kriechi My understanding is that Firefox never sends a HEADERS frame for the streams that it initially sent PRIOIRITY.

**Comment by Lukasa** [comment]
@kazuho That's correct. =)

hyper-h2 doesn't mandate either behaviour: it can send priority information on the headers frame if it wants to, as of 2.4.0. But there is no reason to forbid the other behaviour.

**Comment by Kriechi** [comment]
Yes, you are correct. This is merely how we initially found a problem in mitmproxy - which acts as HTTP/2 proxy, and therefore has to map different stream ids between two connection endpoints.
Wen then reproduced the bug in pure Python with h2 (see code above).

**Comment by kazuho** [comment]
@Lukasa @Kriechi Thank you for the clarification. I was wondering if sending them separately gave us any opportunity to do interesting things (e.g. optimization).

And thank you for the repro test. I assume it has helped @deweerdt resolve the bug.
