### ISSUE TITLE
Emit  _RequestHeadersSent internal event

### ISSUE THREAD

**Issue by sunu** [python-hyper/hyper-h2#314]
In #311 we introduced `_ResponseHeadersSent`. So we should also have a `_RequestHeadersSent` for the sake of symmetry.

**Comment by alexwlchan** [comment]
Our other events don’t include the word "Headers", e.g. `ResponseReceived`, `TrailersSent`.

While we’re doing this refactoring, let’s drop the "Headers", i.e. rename `_ResponseHeadersSent` to `_ResponseSent`, and add a new event `_RequestSent`.

**Comment by alexwlchan** [comment]
Fixed by #320.
