### ISSUE TITLE
docs - basic usage step 4: Handling Events

### ISSUE THREAD

**Issue by anilkunchalaece** [python-hyper/hyper-h2#339]
If use the same code in step4: Handing Events Section i am getting the Following Error

![screenshot from 2016-09-27 21 32 10](https://cloud.githubusercontent.com/assets/17523245/18881677/e791279e-84f9-11e6-9a07-4b0f2678d874.png)

if i changed the Header section to the following it is working
`    headers={b':status': '200'},`

**Comment by alexwlchan** [comment]
I assume you're looking at this page? http://python-hyper.org/projects/h2/en/stable/basic-usage.html#step-4-handling-events

Yes, we seem to be using the deprecated method of passing headers as a dict -- should be a list of tuples. Will fix.

**Comment by alexwlchan** [comment]
[Found it](http://docs.readthedocs.io/en/latest/versions.html):

> We also create a stable version, if your project has any tagged releases. stable will be automatically kept up to date to point at your highest version.

Highest tagged version of hyper-h2 is 2.4.1, which doesn't include this docs fix.

Fix is to cut a new major release of hyper-h2, which will presumably include the shiny new docs fixes, or change the docs to point at latest, not stable &ndash; not sure what @Lukasa prefers.

**Comment by Lukasa** [comment]
I kinda hate having the docs point at `latest`: it causes the API docs to contain things that haven't been released yet. Ideally we'll resolve this by shipping a new release soon.
