### ISSUE TITLE
Frame data missing or invalid

### ISSUE THREAD

**Issue by LazyLemons** [python-hyper/hyper-h2#356]
`kcelik@kcelik-pc:~/http2_server$ hyper GET http://http2bin.org/get`
`Traceback (most recent call last)`:
&nbsp;`File "/usr/local/bin/hyper", line 9, in <module>`
&nbsp;&nbsp;`load_entry_point('hyper==0.7.0', 'console_scripts', 'hyper')()`
&nbsp;`File "/usr/local/lib/python2.7/dist-packages/hyper/cli.py", line 259, in main`
&nbsp;&nbsp;`data = request(args)`
&nbsp;`File "/usr/local/lib/python2.7/dist-packages/hyper/cli.py", line 249, in request`
&nbsp;&nbsp;`response = conn.get_response()`
&nbsp;`File "/usr/local/lib/python2.7/dist-packages/hyper/common/connection.py", line 140, in get_response`
&nbsp;&nbsp;`self._conn._connect_upgrade(e.sock)`
&nbsp;`File "/usr/local/lib/python2.7/dist-packages/hyper/http20/connection.py", line 400, in _connect_upgrade`
&nbsp;&nbsp;`self._recv_cb()`
&nbsp;`File "/usr/local/lib/python2.7/dist-packages/hyper/http20/connection.py", line 771, in _recv_cb`
&nbsp;&nbsp;`self._single_read()`
&nbsp;`File "/usr/local/lib/python2.7/dist-packages/hyper/http20/connection.py", line 669, in _single_read`
&nbsp;&nbsp;`events = conn.receive_data(data)`
&nbsp;`File "/usr/local/lib/python2.7/dist-packages/h2/connection.py", line 1298, in receive_data`
&nbsp;&nbsp;`for frame in self.incoming_buffer:`
&nbsp;`File "/usr/local/lib/python2.7/dist-packages/h2/frame_buffer.py", line 165, in next`
&nbsp;&nbsp;`raise FrameDataMissingError("Frame data missing or invalid")`
`h2.exceptions.FrameDataMissingError: Frame data missing or invalid`

Python 2.7

**Comment by Lukasa** [comment]
Can you provide the output of `pip freeze`, please?

**Comment by LazyLemons** [comment]
> Warning: cannot find svn location for distribute==0.6.24dev-r0
Brlapi==0.5.6
GnuPGInterface==0.3.2
Magic-file-extensions==0.2
Mako==0.5.0
MarkupSafe==0.15
PAM==0.4.2
PIL==1.1.7
PyYAML==3.11
Twisted-Core==11.1.0
Twisted-Names==11.1.0
Twisted-Web==11.1.0
adium-theme-ubuntu==0.3.2
apt-xapian-index==0.44
apturl==0.5.1ubuntu3
argparse==1.2.1
attrs==16.2.0
chardet==2.0.1
command-not-found==0.2.44
configglue==1.0
debtagshw==0.1
defer==1.0.2
devscripts==2.11.6ubuntu1.7
dirspec==3.0.0
## FIXME: could not find svn URL in dependency_links for this package:
distribute==0.6.24dev-r0
duplicity==0.6.18
enum34==1.1.6
h2==2.4.1
hpack==2.3.0
httplib2==0.7.2
hyper==0.7.0
hyperframe==3.2.0
jockey==0.9.7
keyring==0.9.2
language-selector==0.1
launchpadlib==1.9.12
lazr.restfulclient==0.12.0
lazr.uri==1.0.3
lockfile==0.8
louis==2.3.0
nvidia-common==0.0.0
oauth==1.0.1
onboard==0.97.1
oneconf==0.2.8.1
pexpect==2.3
piston-mini-client==0.7.2
protobuf==2.4.1
pyOpenSSL==0.12
pyasn1==0.1.9
pyasn1-modules==0.0.8
pycrypto==2.4.1
pycups==1.9.61
pycurl==7.19.0
pyinotify==0.9.2
pyserial==2.5
pysmbc==1.0.13
python-apt==0.8.3ubuntu7.3
python-dateutil==1.5
python-debian==0.1.21ubuntu1
python-virtkey==0.60.0
pyxdg==0.19
reportlab==2.5
rhythmbox-ubuntuone==4.2.0
service-identity==16.0.0
sessioninstaller==0.0.0
simplejson==2.3.2
software-center-aptd-plugins==0.0.0
system-service==0.1.6
ubuntuone-couch==0.3.0
ubuntuone-installer==3.0.2
ubuntuone-storage-protocol==3.0.2
ufw==0.31.1-1
unattended-upgrades==0.1
unity-lens-video==0.3.5
unity-scope-video-remote==0.3.5
usb-creator==0.2.23
wadllib==1.3.0
wsgiref==0.1.2
xdiagnose==2.5.3
xkit==0.0.0
zope.interface==3.6.1

**Comment by LazyLemons** [comment]
maybe ssl backport related? python 2.7.12 works

**Comment by Lukasa** [comment]
Nope, this can't be the ssl backport problem, because you're using plaintext HTTP/2 via upgrade. What version of Python 2.7 are you using when you get the failure?

**Comment by LazyLemons** [comment]
I am using 2.7.3.

**Comment by Lukasa** [comment]
I think that version of Python has some problems with memoryviews, which hyper uses extensively. You should find a newer version of 2.7 works better (and you should upgrade anyway, 2.7.3 is *ancient*).
