### ISSUE TITLE
Provide SettingsEnum to dynamically list and print

### ISSUE THREAD

**Issue by Kriechi** [python-hyper/hyper-h2#359]
Similar to #303

It would be nice to have a list/dict/enum of all valid settings (key + names).
This can be useful for printing debug information or just plain logging of changed settings.

**Comment by Lukasa** [comment]
This is a really good idea. If anyone wants to pick this up it should be pretty easy, and requires relatively little HTTP/2 knowledge. A good first issue to tackle.

**Comment by drpoggi** [comment]
I'd like to pick this up if no one has gotten to it yet.

**Comment by Lukasa** [comment]
I believe that no-one is working on this at the moment, so you should feel free.
