### ISSUE TITLE
Provide base class for events

### ISSUE THREAD

**Issue by Kriechi** [python-hyper/hyper-h2#369]
Right now I'm trying to add more type information to the mitmproxy HTTP/2 stack and stumbled upon the fact that alle h2 events are just objects. I would like to see a generic `h2.events.Event` class or something similar.
Does it make sense to provide a base class for all events?

**Comment by SethMichaelLarson** [comment]
I suggested this a while ago but didn't create a PR. I'm sure it would be pretty easy to create. :)

**Comment by Lukasa** [comment]
Yup, this would be necessary for defining events. I'm happy to have a no-op base class.
