### ISSUE TITLE
hyper-h2-2.5.0 test failures

### ISSUE THREAD

**Issue by dol-sen** [python-hyper/hyper-h2#371]
Hi, I am the gentoo package maintainer for hyper-h2 as part of the buildbot group of pkgs that I maintain.
It appears that the test suite is missing the helpers.py and coroutine_tests.py files from the tarball.  I also see test/conftest.py in the main repo is also not included.  I had not added the test capability to the ebuild before this release.

Are any of these tests not relavent for testing on user systems?  ie: pre-release sanity tests.

` >>> Source compiled.

> > > Test phase: dev-python/hyper-h2-2.5.0
> > > - python2_7: running distutils-r1_run_phase python_test
> > >   ========================================================== test session starts ===========================================================
> > >   platform linux2 -- Python 2.7.12, pytest-3.0.3, py-1.4.31, pluggy-0.4.0 -- /usr/bin/python2.7
> > >   cachedir: .cache
> > >   rootdir: /var/tmp/portage/dev-python/hyper-h2-2.5.0/work/h2-2.5.0, inifile: 
> > >   plugins: hypothesis-3.5.3, xdist-1.15.0, cov-2.3.1
> > >   collecting ... collected 685 items / 2 errors

================================================================= ERRORS =================================================================
_______________________________________________ ERROR collecting test/test_basic_logic.py ________________________________________________
ImportError while importing test module '/var/tmp/portage/dev-python/hyper-h2-2.5.0/work/h2-2.5.0/test/test_basic_logic.py'.
Original error message:
'No module named helpers'
Make sure your test modules/packages have valid Python names.
____________________________________________ ERROR collecting test/test_interacting_stacks.py ____________________________________________
ImportError while importing test module '/var/tmp/portage/dev-python/hyper-h2-2.5.0/work/h2-2.5.0/test/test_interacting_stacks.py'.
Original error message:
'No module named coroutine_tests'
Make sure your test modules/packages have valid Python names.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================== 2 error in 1.27 seconds =========================================================
- ERROR: dev-python/hyper-h2-2.5.0::gentoo failed (test phase):
-   Tests failed under python2.7
  `

**Comment by Lukasa** [comment]
Hi @dol-sen! I presume you obtained your tarball from PyPI, is that correct? Generally speaking I don't ship tests or test fixtures in the PyPI sdist, as they aren't relevant for installation purposes. However, I'm willing to be talked around on that point I think.

The two files in question are fairly important if you want to test the good function of this library, though I should note that this library has *very* minimal interaction with the wider system and is extremely unlikely to break in gentoo.

**Comment by Lukasa** [comment]
@dol-sen Just a quick prompt to check if this is still a problem for you.

**Comment by dol-sen** [comment]
Yeah, Since you said the tests are not really important for integration, It doesn't matter to me, but if you decide to not include the missing files, then maybe you should remove all the tests that are shipped in the tarball.  I'm fine with either way.
