### ISSUE TITLE
Implement equality for the Settings object.

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/hyper-h2#453]
In #452 we merged a patch that resolved a functional issue, but the test relied on implementation details of one of our classes (`h2.settings.Settings`). It would be preferable if we could avoid that, which is best done by implementing equality for that object.

There isn't urgency on this, this would largely be a convenience feature. However, it would be nice to land this before we ship 2.6.0. This is a great patch for someone who doesn't know much about HTTP/2 but wants some OSS Python to do, as this is a nicely well-defined bit of functionality: implement the equality interface for Python 2 and 3, test it, and then fix up the test merged in #452 to use it.

Anyone who wants to may take a shot at this patch.

**Comment by bhavishyagopesh** [comment]
@Lukasa, Hey,beginner here, could you please give me details, I would like make my first PR.

**Comment by Lukasa** [comment]
@bhavishyagopesh So what you'd need to do for this is as follows:

1. Look into how Python implements equality for user-defined objects. Generally this is done by specifying two magic methods: `__eq__` and `__ne__`.
2. You'd need to implement this for the `Settings` class.
3. You'd then want to write some tests to confirm that equality works as expected.

What further detail would you need? I'm inclined to not want to initially give too much assistance so that you can do as much work on your own as possible, but if you need further help I'm happy to give it.

**Comment by bhavishyagopesh** [comment]
@Lukasa,Thanks,I will first try on my own, and in case I get stuck , I'll ask you.

**Comment by bhavishyagopesh** [comment]
@Lukasa, as you said,I added __eq__ and __ne__ but I couldn't understand how to write test.And also, I'm facing issues running test_h2_upgrade.py .

**Comment by Lukasa** [comment]
So to write tests you'll want to write them in the `test_settings.py` file. You can see several other tests in there. You want to write tests that confirm that Settings objects that should be equal are equal, and those that aren't equal aren't.

Note: to run the tests, you'll need to use a tool called [tox](https://tox.readthedocs.io/en/latest/). Using that tool may help fix your testing problems.

**Comment by bhavishyagopesh** [comment]
I wrote tests in test_settings.py, and ran tox, it showed an error involving '_validate_setting'.So should I send the pull request?

**Comment by Lukasa** [comment]
You certainly can do, and we can use the output from the CI suite to check what's going on.

**Comment by bhavishyagopesh** [comment]
I made the pull request...

**Comment by bhavishyagopesh** [comment]
tox is showing AssertionError with 

> "assert not s1 == s2"


 not s1==s2

**Comment by Lukasa** [comment]
Resolved by #464 and #465.
