### ISSUE TITLE
Update test_h2_upgrade to use new Settings equality tools.

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/hyper-h2#467]
Follows on from #464 and #465.

Now that `Settings` objects can be compared properly for equality, we should fixup `test/test_h2_upgrade.py` to use this comparison method in `test_client_settings_are_applied`, which currently uses private implementation details to compare `Settings` objects. This is an easy one, and a natural next step for @bhavishyagopesh if they're interested.

**Comment by Riyuzakii** [comment]
@Lukasa I'm a first timer and i would like to contribute if its alright. some instructions on how to proceed would be nice and i don't know how the 'Testing' thing works.

**Comment by Lukasa** [comment]
@Riyuzakii So learning about testing is somewhat beyond the scope of what I can do to help you remotely. I highly recommend you attempt to find some resources that introduce the idea of "unit testing" (which is what this issue covers).

As to this specific issue, the requirement is to change a specific test. The file and the name of the test are in my comment above, and the specific requirement is to change that test to compare two `Settings` objects directly, rather than comparing them by their fields.
