### ISSUE TITLE
Recv frame on closed state should be connection error or stream error

### ISSUE THREAD

**Issue by chhsiao90** [python-hyper/hyper-h2#470]
Currently, hyper-h2 always send stream error when received unexpected frame on stream in closed state.

But in [rfc7540#section-5.1](https://tools.ietf.org/html/rfc7540#section-5.1)
> An endpoint MUST NOT send frames other than PRIORITY on a closed
      stream.  An endpoint that receives any frame other than PRIORITY
      after receiving a RST_STREAM MUST treat that as a stream error
      (Section 5.4.2) of type STREAM_CLOSED.  Similarly, an endpoint
      that receives any frames after receiving a frame with the
      END_STREAM flag set MUST treat that as a connection error
      (Section 5.4.1) of type STREAM_CLOSED, unless the frame is
      permitted as described below.

Which action should be taken, connection error or stream error, depends on how the stream had been closed.
If stream is closed by RST_STREAM, it should return stream error when received unexpected frame.
If stream is closed by END_STREAM, it should return connection error when received unexpected frame.

**Comment by Lukasa** [comment]
Yup, this sounds like a reasonable change.

**Comment by chhsiao90** [comment]
I would like to work on this issue.
I think that the PR solved this may have some major change on the code.
So I will ask your advise that which to change will better.

One idea is added a field in the state machine of stream called ```stream_closed_by``` that had state how this stream is closed by.
Here is the code https://github.com/chhsiao90/hyper-h2/commit/9b5ad36ad7b4de833b362c163665cc12d64178b4

And will add the logic at ```H2StreamStateMachine#send_on_closed_stream``` and a new function ```send_on_closed_stream#recv_on_closed_stream```

WDYT

**Comment by Lukasa** [comment]
I think that approach is reasonable, if you open a PR I'll provide more feedback on the specifics. 👍

**Comment by chhsiao90** [comment]
No problem, I will keep working on that and will create a PR soon!

**Comment by Lukasa** [comment]
Resolved by #472.
