### ISSUE TITLE
pypi package missing content

### ISSUE THREAD

**Issue by caronc** [python-hyper/hyper-h2#506]
A minor issue I noticed while trying to build your packages for CentOS/RedHat 7.x.
It appears the [packages provided on pypi](https://pypi.python.org/pypi/h2/2.6.1) (specifically the [direct link](https://pypi.python.org/packages/ad/5d/c3015afe621924f7ec5f645476780fef3ac1d32cd256ce2705b50c152026/h2-2.6.1.tar.gz)) has missing content vs what you provide on your github page (here) in you [2.6.1 release](https://github.com/python-hyper/hyper-h2/releases/tag/v2.6.1).

The only missing ones that really matter (to me and probably others) are:
* test/conftest.py
* test/coroutine_tests.py
* test/helpers.py

At the end of the day, I hauled in your copy from github (which contains these files of course) and all tests pass with flying colors (as you already knew it would) :)

So do what you wish with this info; and thank you and your awesome community for all of the great work on this solid piece of code!

**Comment by Lukasa** [comment]
Thanks for this report! This was fixed in the 3.0 release, so I strongly recommend moving to the latest and greatest, which should also rectify your packaging problems. 

Thanks for reaching out! 😁
