### ISSUE TITLE
Add a Curio example

### ISSUE THREAD

**Issue by Lukasa** [python-hyper/hyper-h2#51]
Why not? @dabeaz has written a 3.5-only async library called [curio](https://github.com/dabeaz/curio). He claims it's "barely in a prerelease state", but why not give it a chance to show us what it can do by having an example for it. More examples can only be better!

**Comment by kumarSC** [comment]
Hi @Lukasa ,  I am a mobile developer and a starter on open source projects. I want to contribute to open source starting with small things as I learn.I found this issue on github with tag documentation.Could you please suggest how I can get started on this issue?

**Comment by Lukasa** [comment]
@kumarSC The "documentation" tag here is potentially a bit misleading: the goal here is to write a code example. I have similar examples [here](https://github.com/python-hyper/hyper-h2/blob/master/examples/eventlet/eventlet-server.py), and intend to write a new one along those lines but using [curio](https://github.com/dabeaz/curio). This may not be best suited as a new task, unless you're comfortable writing Python code.

**Comment by dabeaz** [comment]
As note: curio is a very immature project right now.  However, it can provide a stream-oriented interface on top of a socket. Could it be used? Maybe.   Having HTTP run on top of it would kind of awesome.  I can offer help if someone is interested.

**Comment by Lukasa** [comment]
I have a long flight tomorrow, so I may kick the tires on curio while I'm on it: see if I can get it to do what I need.
