### ISSUE TITLE
API changes to Ping events

### ISSUE THREAD

**Issue by Kriechi** [python-hyper/hyper-h2#834]
Similar to https://github.com/python-hyper/wsproto/pull/36, I would appreciate bringing the h2 API & events into a similar state as wsproto.

At the moment h2 fires a `PingAcknowledged` event when it receives a PING frame with the ACK flag. But it does not fire an event for receiving an initial PING.

I would propose introducing a new event: `PingReceived`,
and renaming the existing `PingAcknowledged` to `PingAckReceived`.
Both events should carry the `frame.opaque_data` as `ping_data` attribute.

For backward-compatibility `PingAcknowledged` should be an empty subclass of `PingAckReceived`, and be marked as deprecated.

**Comment by Lukasa** [comment]
So I agree that having a `PingReceived` event is a good idea: that seems like a no-brainer. I'm confused about the rationale for changing the name of `PingAcknowledged`: why make this API change?

**Comment by Kriechi** [comment]
`PingAcknowledged`: just a cosmetic change to somewhat resemble the same naming scheme as wsproto, but since HTTP/2 doesn't have a `PONG`, but merely a `Ping+Ack`.

`PingReceived` & `PingAckReceived` fits together better IMO.

**Comment by Kriechi** [comment]
To elaborate a bit more:
`PingAcknowledged` sounds to me as if hyper-h2 **did something** (i.e., send a ping acknowledgement), but this is actually **not** the case. We only received a frame.

Might be a borderline technicality, but IMHO using `...Received` events is easier to understand.
