### ISSUE TITLE
Auto-ACK Settings

### ISSUE THREAD

**Issue by Kriechi** [python-hyper/hyper-h2#88]
Hi,

In your docs it [is stated](https://github.com/python-hyper/hyper-h2/blob/ec5fb452e3f79a29dc36c6cdd77a3d3d50afd710/h2/events.py#L97-L99):
> In HTTP/2, settings changes need to be acknowledged. hyper-h2 does not
> automatically acknowledge them, because it is possible that the caller may
> not be happy with the changed setting (or would like to know about it).

Could you elaborate on why the caller "might not be happy" with the changes?
There is no negotiation of settings, either you ACK them, or you get a GoAway or something, as far as I understand it? Creating a `RemoteSettingsChanged` by itself is nice to have, but manually having to ACK them is IMHO not necessary, it would be cleaner to handle that the same way pings are auto-handled.

Or am I missing some important edge-case?
Thanks for the explanation.

P.S. I know it is only 2 LOCs, but still - if we could put these lines into `hyper-h2` I think it is easier to use.

**Comment by Lukasa** [comment]
@Kriechi I am 50/50 on this.

So, you're correct that there's no negotiation of settings. However, if a user receives a settings value they do not like (e.g. `SETTINGS_MAX_CONCURRENT_STREAMS` set to `0`, which will temporarily disallow the creation of new streams), they may prefer to send a GOAWAY than to acknowledge the settings. This makes it possible to avoid sending a potentially misleading SETTINGS ACK, when the settings have not actually been acknowledged.

With that said, I'm open to being convinced that this is actually such a minor use-case that we don't need to allow it.

**Comment by Kriechi** [comment]
Sending a GoAway instead of SettingsAck makes sense - but I would guess that is very uncommon.

As discussed earlier, maybe the default behaviour of hyper-h2 could be to ACK new settings automatically - and the user can disable this during H2Connection instantiation.

**Comment by Lukasa** [comment]
I'm beginning to lean towards simply removing this as an option: automatically acknowledge the settings, and not worry about the desire to say GOAWAY in response. If we really find we need the flag we can add it in later.
